Develop
culturecreates/footlight-calendar-widget pull request #50
Opened 2024-10-18 09:41 UTC by SyamBabu-M

2024-10-18 21:56 UTC, saumier requested changes

2024-10-18 21:56 UTC, saumier commented on .github/workflows/build-production-deploy-s3.yml
> +          previous_major_version=$((major_version - 2))
@SyamBabu-M Please leave all major versions. Do not delete major_version - 2.

2024-10-18 21:56 UTC, saumier commented on .github/workflows/build-production-deploy-s3.yml
> +          aws s3 sync ./build s3://${{env.WEBHOSTING_BUCKET_NAME}}/v${major_version}/ --acl public-read --cache-control max-age=3600
I think you are missing a delete command to remove old files from the directory. Try  `--acl public-read --cache-control max-age=3600 --delete `

2024-10-18 22:06 UTC, saumier requested changes

2024-10-18 22:06 UTC, saumier commented on config-overrides.js
> +module.exports = function override(config, env) {
@SyamBabu-M I wondering why you are changing the name of the .js and .css files as well as the path.  I think changing both the filenames and the path is redundant. I propose you change the path (by adding `v0`) but keep the filenames for .js and .css without any version.  Let me know if you a reason to add the version to the filenames.

2024-10-21 09:22 UTC, SyamBabu-M commented on config-overrides.js
> +module.exports = function override(config, env) {
I agree. It seems redundant to add the version number to both the directory and .js and CSS files. I will update the .js and .css files to widget.js and widget.css respectively

2024-10-21 14:57 UTC, saumier approved these changes

2024-10-23 09:33 UTC, merged